# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=2000
SAVEHIST=1000
unsetopt beep
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/radissimo/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Load ability to read git info
autoload -Uz vcs_info
precmd() { vcs_info }

zstyle ':vcs_info:git:*' formats '%b '

# Format prompt
setopt PROMPT_SUBST
PROMPT='%F{161}%*%f %F{255}%n%f %F{118}%~%f %F{59}${vcs_info_msg_0_}%f$ '
